### PR TITLE
feature/salary-list

### PR DESCRIPTION
**Pull request by nghianguyent**

### CODE REVIEW

**Comment by nghia14302** [comment]
Task linked: [CU-865byhj09 Supply contact](https://app.clickup.com/t/865byhj09)

**Comment by nghia14302** [comment]
Task linked: [CU-865byfrv2 Hello](https://app.clickup.com/t/865byfrv2)

**Comment by nghianguyent** [comment]
Task linked: [CU-865bz16ne DEmo](https://app.clickup.com/t/865bz16ne)

**Comment by nghianguyent** [comment]
Hello

**Pull request merged**
